### ISSUE TITLE
Are the RSS items cached?

### ISSUE THREAD

**Issue by vmassol** [w3stling/rssreader#100]
Hello,

I've just noticed that my RSS feed source has changed content but the data I get from `RssReader` is still the old data. Does it have a cache? If so, is that configurable? I'm on version 3.4.0.

Thanks a lot!

**Comment by w3stling** [comment]
There is no caches in `RssReader`.
`java.net.http.HttpClient` is used for fetching the RSS feed data and no caching of http responses exists there as far as I know.

If you fetch the RSS feed data with `wget` or `curl` command do you see old data then?

Do you get the same result with the latest version of `RssReader`?
