### ISSUE TITLE
How to get all image?

### ISSUE THREAD

**Issue by Deichor** [w3stling/rssreader#115]
I have about 700 different RSS sources and lots of different image formats. How do I detect all images in these?

**Comment by w3stling** [comment]
How to get the channel image from an item object.
```Java
Optional<Image> channelImage = item.getChannel().getImage();
```

Example that prints the RSS channel title and the URL to the image for all RSS channels.
```Java
List<String> urlList = List.of(URL1, URL2, URL3, URL4, URL5);
new RssReader().read(urlList)
               .map(Item::getChannel)
               .distinct()
               .filter(channel -> channel.getImage().isPresent())
               .forEach(channel -> System.out.printf("RSS channel: %s, Image URL: %s\n", channel.getTitle(), channel.getImage().get().getUrl()));
```

**Comment by Deichor** [comment]
> How to get the channel image from an item object.
> 
> ```java
> Optional<Image> channelImage = item.getChannel().getImage();
> ```
> 
> Example that prints the RSS channel title and the URL to the image for all RSS channels.
> 
> ```java
> List<String> urlList = List.of(URL1, URL2, URL3, URL4, URL5);
> new RssReader().read(urlList)
>                .map(Item::getChannel)
>                .distinct()
>                .filter(channel -> channel.getImage().isPresent())
>                .forEach(channel -> System.out.printf("RSS channel: %s, Image URL: %s\n", channel.getTitle(), channel.getImage().get().getUrl()));
> ```

Most sources use a different image format. So, not all of them have channel images that I can access.

**Comment by w3stling** [comment]
> Most sources use a different image format. So, not all of them have channel images that I can access.

Can you clarify what you mean with different image format? Do you have an example?

If the channel image url is available in a different tag then it possible to add a channel extension to mapp channel image url from a different tag.

Example mapp value in custom tag `/rss/channel/picture` to `image.getUrl()`:
```java
new RssReader().addChannelExtension("picture", (channel, value) -> Mapper.createIfNull(channel::getImage, channel::setImage, Image::new).setUrl(value))
               .read(urlList)
               .map(Item::getChannel)
               .distinct()
               .filter(channel -> channel.getImage().isPresent())
               .forEach(channel -> System.out.printf("RSS channel: %s, Image URL: %s\n", channel.getTitle(), channel.getImage().get().getUrl()));
```

For Atom feed `icon` and `logo` tags are mapped to `channel.getImage()`

**Comment by w3stling** [comment]
Closing issue. Feel free to reopen if it is still a problem.
