### ISSUE TITLE
[FEATURE REQUEST] Parse String directly.

### ISSUE THREAD

**Issue by GrenderG** [w3stling/rssreader#134]
Would be nice to have a `read()` method capable of parsing a `String` containing a feed directly. At this moment you need to convert the `String` to `byte[]` and then to `ByteArrayInputStream`.

**Comment by w3stling** [comment]
Currently the `read(String)` method takes a URL as input. It would be good to avoid doing a breaking change for this.

Do you have any suggestion how the method signature should look like?

**Comment by w3stling** [comment]
Fixed by PR #180 
Included release 3.9.0
