### ISSUE TITLE
Support for multiple instances of Enclosure

### ISSUE THREAD

**Issue by Vodes** [w3stling/rssreader#137]
I'm not sure if this would be out of scope or not but torznab feeds have the ability to contain multiple enclosures.
The spec for that is [here](https://torznab.github.io/spec-1.3-draft/revisions/1.0-Torznab-Torrent-Support.html).

I would greatly appreciate if this was possible to add.

**Comment by w3stling** [comment]
Multiple enclosure is not part of the RSS standard however it used and supported by other software.
https://validator.w3.org/feed/docs/warning/DuplicateEnclosure.html

I have added support for multiple enclosures in PR #140

It is included in the [1.6.0](https://github.com/w3stling/rssreader/releases/tag/v3.6.0) release.

**Comment by melloware** [comment]
@w3stling didn't know where else to post this but just wanted to say thanks for this great library.  We are switching off of Rome to this library specifically because of Zero Dependencies.  But really great job!

See: https://github.com/primefaces/primefaces/issues/11789
