### ISSUE TITLE
how to get the text of news?

### ISSUE THREAD

**Issue by bagherfathi** [w3stling/rssreader#2]
how to get the text of news?

**Comment by w3stling** [comment]
See test cases for example on how to extract text from news feeds.
https://github.com/w3stling/rssreader/blob/master/src/test/java/com/apptastic/integrationtest/RssReaderIntegrationTest.java

Javadoc
https://w3stling.github.io/rssreader/javadoc/2.0.1/com.apptastic.rssreader/com/apptastic/rssreader/package-summary.html
