### ISSUE TITLE
blank enclosure length leads to exception

### ISSUE THREAD

**Issue by ArloL** [w3stling/rssreader#38]
First of all many thanks for this lib :) I started experimenting with it today and it's been great.

One thing I came across: one of the feeds I am trying to consume has the enclosure length set to blank (`length=""`). Sadly this breaks here:

https://github.com/w3stling/rssreader/blob/e29cf63140c74883ff0e575ec4ae55d10e938106/src/main/java/com/apptasticsoftware/rssreader/AbstractRssReader.java#L148

According to the spec the value must be set - so the feed is doing it wrong. Nonetheless I was wondering if there is a way for the code to do something reasonable and came up with this locally:

```
enclosureAttributes
		.put("length", (i, v) -> i.getEnclosure().ifPresent(e -> {
			if (!v.isBlank()) {
				e.setLength(Long.parseLong(v));
			}
		}));
```

In accordance with the Robustness principle it doesn't seem like the worst idea to me.

What do you think?

If you think it's reasonable, I could create a PR.

**Comment by w3stling** [comment]
Yep - agreed here, thanks for catching that @ArloL.
Please open a PR.
