### ISSUE TITLE
Response http status code: 401

### ISSUE THREAD

**Issue by newthings4learning** [w3stling/rssreader#5]
Hi,

I am getting the below exception on this line -rssReader.read(URL) 
`java.io.IOException: java.util.concurrent.ExecutionException: java.io.IOException: Response http status code: 401`

how can we pass the credentials ?

thanks !

**Comment by w3stling** [comment]
RssReader constructor accepts an HttpClient object. That HttpClient object can be configured with an Authenticator that handles that authentication.
