### ISSUE TITLE
Support read from file

### ISSUE THREAD

**Issue by leotu** [w3stling/rssreader#7]
After read from remote successfully, I would store it into storage (i.e, local file system)  for next time read faster.
There is no method to read from String or Bytes :-(

**Comment by w3stling** [comment]
I added a method for reading an RSS feed from an InputStream object. Available in version 2.4.1.

```java
String rssText = getRssFeedAsText()
InputStream inputStream = new ByteArrayInputStream(rssText.getBytes(StandardCharsets.UTF_8));

RssReader reader = new RssReader();
List<Item> items = reader.read(inputStream).collect(Collectors.toList());
```
